### ISSUE TITLE
Makes souremaps unusable

### ISSUE THREAD

**Issue by freeall** [call-a3/browserify-notify#1]
If I use `browserify -d -p browserify-notify` all the sourcemaps are incorrect and point to wrong files/lines.

I know it's been 2 years since there's been activity in this repo, but do you have any ideas on how to fix it? I could give it a go.

**Comment by call-a3** [comment]
Since this plugin doesn't alter sources/bundles/... in any way, I couldn't imagine how it could make sourcemaps be incorrect. Are you sure the sourcemaps were correct to start with (without using this plugin?). You can see for yourself in the index.js file that no sources are touched or modified.
